name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --package super_cell --all-features --verbose
    - name: Build Release
      run: cargo build --package super_cell --all-features --release --verbose
    - name: Run tests
      run: cargo test --package super_cell --lib tests --all-features --verbose
    - name: Run tests release
      run: cargo test --package super_cell --lib tests --all-features --release --verbose
